# Generated by Django 4.2.13 on 2026-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='アイキャッチ画像')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ一覧',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_stats', 'ホーム: 実績数値'), ('home_skills', 'ホーム: 技術スタック'), ('services', 'サービス一覧'), ('portfolio', '実績・ポートフォリオ'), ('profile_values', 'プロフィール: こんな人です'), ('profile_career', 'プロフィール: キャリア'), ('profile_apps', 'プロフィール: 制作アプリ'), ('profile_skills', 'プロフィール: 技術スタック')], max_length=30, verbose_name='セクション')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_items/', verbose_name='画像')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='content_items/', verbose_name='画像2')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コンテンツ項目',
                'verbose_name_plural': 'コンテンツ項目一覧',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='キー')),
                ('value', models.TextField(blank=True, verbose_name='値')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイトテキスト',
                'verbose_name_plural': 'サイトテキスト一覧',
                'ordering': ['key'],
            },
        ),
    ]
