# Generated by Django 4.2.13 on 2026-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_fix_picsco_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='section',
            field=models.CharField(choices=[('home_stats', 'ホーム: 実績数値'), ('home_skills', 'ホーム: 技術スタック'), ('services', 'サービス一覧'), ('portfolio', '実績・ポートフォリオ'), ('profile_values', 'プロフィール: こんな人です'), ('profile_career', 'プロフィール: キャリア'), ('profile_apps', 'プロフィール: 作成物'), ('profile_skills', 'プロフィール: 技術スタック')], max_length=30, verbose_name='セクション'),
        ),
    ]
