from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    ContactDetailView,
    ContactListView,
    CustomerDetailView,
    CustomerInviteView,
    CustomerListCreateView,
    DiaryDetailView,
    DiaryListCreateView,
    LabReservationDetailView,
    LabReservationListView,
    LabReservationSettingsView,
    LabTokenObtainPairView,
    MeView,
    RoleDetailView,
    RoleListCreateView,
    SetPasswordView,
    TaskDetailView,
    TaskListCreateView,
    UserDetailView,
    UserListCreateView,
)

urlpatterns = [
    path('auth/login', LabTokenObtainPairView.as_view()),
    path('auth/refresh', TokenRefreshView.as_view()),
    path('auth/me', MeView.as_view()),
    path('lab/set-password', SetPasswordView.as_view()),
    path('lab/contacts', ContactListView.as_view()),
    path('lab/contacts/<int:pk>', ContactDetailView.as_view()),
    path('lab/customers', CustomerListCreateView.as_view()),
    path('lab/customers/<int:pk>', CustomerDetailView.as_view()),
    path('lab/customers/<int:pk>/invite', CustomerInviteView.as_view()),
    path('lab/tasks', TaskListCreateView.as_view()),
    path('lab/tasks/<int:pk>', TaskDetailView.as_view()),
    path('lab/diaries', DiaryListCreateView.as_view()),
    path('lab/diaries/<int:pk>', DiaryDetailView.as_view()),
    path('lab/reservations', LabReservationListView.as_view()),
    path('lab/reservations/<int:pk>', LabReservationDetailView.as_view()),
    path('lab/reservation-settings', LabReservationSettingsView.as_view()),
    path('lab/users', UserListCreateView.as_view()),
    path('lab/users/<int:pk>', UserDetailView.as_view()),
    path('lab/roles', RoleListCreateView.as_view()),
    path('lab/roles/<int:pk>', RoleDetailView.as_view()),
]
