# Generated by Django 4.2.13 on 2026-07-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0003_customer_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '営業時間',
                'verbose_name_plural': '営業時間一覧',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='予約単位(分)')),
                ('min_notice_hours', models.PositiveIntegerField(default=24, verbose_name='最短予約受付(時間前)')),
                ('max_advance_days', models.PositiveIntegerField(default=60, verbose_name='予約可能日数(何日先まで)')),
            ],
            options={
                'verbose_name': '予約設定',
                'verbose_name_plural': '予約設定',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='開始日時')),
                ('end_at', models.DateTimeField(verbose_name='終了日時')),
                ('status', models.CharField(choices=[('confirmed', '確定'), ('cancelled', 'キャンセル')], default='confirmed', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lab.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約一覧',
                'ordering': ['start_at'],
            },
        ),
    ]
