# Generated by Django 4.2.13 on 2026-07-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ロール名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ロール',
                'verbose_name_plural': 'ロール一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(blank=True, related_name='members', to='lab.role', verbose_name='ロール')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labユーザープロフィール',
                'verbose_name_plural': 'Labユーザープロフィール一覧',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('source_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='contact.contactmessage', verbose_name='元のお問い合わせ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Labログインアカウント')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(choices=[('contacts', 'お問い合わせ一覧'), ('customers', '顧客管理'), ('tasks', 'タスク一覧'), ('diary', '日記'), ('users', 'ユーザー管理'), ('roles', '権限管理')], max_length=30, verbose_name='メニュー')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '権限なし'), (1, '参照'), (2, '参照・編集')], default=0, verbose_name='権限レベル')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='lab.role')),
            ],
            options={
                'verbose_name': 'ロールメニュー権限',
                'verbose_name_plural': 'ロールメニュー権限一覧',
                'unique_together': {('role', 'menu_key')},
            },
        ),
    ]
