# Generated by Django 4.2.13 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_role_userprofile_customer_rolemenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe顧客ID'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('contacts', 'お問い合わせ一覧'), ('customers', '顧客管理'), ('tasks', 'タスク一覧'), ('diary', '日記'), ('reservations', '予約管理'), ('users', 'ユーザー管理'), ('roles', '権限管理')], max_length=30, verbose_name='メニュー'),
        ),
    ]
