# Generated by Django 4.2.13 on 2026-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_customer_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('contacts', 'お問い合わせ一覧'), ('customers', '顧客管理'), ('tasks', 'タスク一覧'), ('diary', '日記'), ('reservations', '予約管理'), ('users', 'ユーザー管理'), ('roles', '権限管理'), ('announcements', 'お知らせ管理'), ('site_content', 'サイトコンテンツ管理')], max_length=30, verbose_name='メニュー'),
        ),
    ]
