# Generated by Django 4.2.13 on 2026-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_rolemenupermission_menu_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メモ',
                'verbose_name_plural': 'メモ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('contacts', 'お問い合わせ一覧'), ('customers', '顧客管理'), ('tasks', 'タスク一覧'), ('diary', '日記'), ('memo', 'メモ'), ('reservations', '予約管理'), ('users', 'ユーザー管理'), ('roles', '権限管理'), ('announcements', 'お知らせ管理'), ('site_content', 'サイトコンテンツ管理')], max_length=30, verbose_name='メニュー'),
        ),
    ]
