# Generated by Django 4.2.13 on 2026-09-24 10:43

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_memo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='lab.labtask', verbose_name='先行タスク'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='duration_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999'))], verbose_name='期間(稼働日)'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='lab.labtask', verbose_name='親タスク'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=10, verbose_name='優先度'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='進捗(%)'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='labtask',
            name='status',
            field=models.CharField(choices=[('todo', '未着手'), ('in_progress', '進行中'), ('review', 'レビュー中'), ('done', '完了'), ('on_hold', '保留'), ('cancelled', '中止')], default='todo', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('contacts', 'お問い合わせ一覧'), ('customers', '顧客管理'), ('tasks', 'タスク管理'), ('diary', '日記'), ('memo', 'メモ'), ('reservations', '予約管理'), ('users', 'ユーザー管理'), ('roles', '権限管理'), ('announcements', 'お知らせ管理'), ('site_content', 'サイトコンテンツ管理')], max_length=30, verbose_name='メニュー'),
        ),
    ]
